### PR TITLE
fix #1: make cards more responsive, fix duplication of stats

### LINKED ISSUE #1: Display of numbers on counters
There seems to be some duplication of the numbers on the counters page when shown on the desktop:

image

It also gets very wide when full screen on a desktop; perhaps all the numbers could just be in the blue boxes like on mobile?

### PR DESCRIPTION
**Pull request by georgejkaye**

### CODE REVIEW

**Comment by georgejkaye** [comment]
Experimented with adding `flex: 1` to `.counterCard` so the cards grow to fill the page width, but this leads to the bottom ones being bigger, which looked a bit weird.

image

**Comment by georgejkaye** [comment]
Also I'm not fully sure about the semantics of the different counts, so we might want to tweak which stats are shown (and subsequently the widths of the boxes)

**Comment by JonFreer** [comment]
Is this the desired formatting: 
image

Can't say I love the non-uniform layout.

Also, we should think about what is the key information. Probably the weekly users as that is what the list is sorted by.

**Comment by JonFreer** [comment]
I do like the dark mode though!

**Comment by georgejkaye** [comment]
This is not the desired formatting

**Comment by georgejkaye** [comment]
Current quick fix: set counter cards to always be 525px, except when screen size is less than that.
How do we feel about the gap on the right?

image

**Comment by georgejkaye** [comment]
Have also removed the word 'user' from the stats to give us more space
image

**Comment by JonFreer** [comment]
Looks good, fix the center alignment and outer margins and I will merge.

**Comment by georgejkaye** [comment]
Centre alignment of what

**Comment by georgejkaye** [comment]
Margin fixed
image

**Comment by JonFreer** [comment]
Centre alignment of the counters on the page. 

Like so:
image

**Comment by georgejkaye** [comment]
gotcha

**Comment by georgejkaye** [comment]
image

**Pull request merged**
